/*
 * This file is generated by jOOQ.
 */
package net.dualsoft.blockbuster.db.jooq.tables.daos;


import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import net.dualsoft.blockbuster.db.jooq.tables.Payment;
import net.dualsoft.blockbuster.db.jooq.tables.records.PaymentRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PaymentDao extends DAOImpl<PaymentRecord, net.dualsoft.blockbuster.db.jooq.tables.pojos.Payment, Integer> {

    /**
     * Create a new PaymentDao without any configuration
     */
    public PaymentDao() {
        super(Payment.PAYMENT, net.dualsoft.blockbuster.db.jooq.tables.pojos.Payment.class);
    }

    /**
     * Create a new PaymentDao with an attached configuration
     */
    public PaymentDao(Configuration configuration) {
        super(Payment.PAYMENT, net.dualsoft.blockbuster.db.jooq.tables.pojos.Payment.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(net.dualsoft.blockbuster.db.jooq.tables.pojos.Payment object) {
        return object.getPaymentId();
    }

    /**
     * Fetch records that have <code>payment_id IN (values)</code>
     */
    public List<net.dualsoft.blockbuster.db.jooq.tables.pojos.Payment> fetchByPaymentId(Integer... values) {
        return fetch(Payment.PAYMENT.PAYMENT_ID, values);
    }

    /**
     * Fetch a unique record that has <code>payment_id = value</code>
     */
    public net.dualsoft.blockbuster.db.jooq.tables.pojos.Payment fetchOneByPaymentId(Integer value) {
        return fetchOne(Payment.PAYMENT.PAYMENT_ID, value);
    }

    /**
     * Fetch records that have <code>customer_id IN (values)</code>
     */
    public List<net.dualsoft.blockbuster.db.jooq.tables.pojos.Payment> fetchByCustomerId(Short... values) {
        return fetch(Payment.PAYMENT.CUSTOMER_ID, values);
    }

    /**
     * Fetch records that have <code>staff_id IN (values)</code>
     */
    public List<net.dualsoft.blockbuster.db.jooq.tables.pojos.Payment> fetchByStaffId(Short... values) {
        return fetch(Payment.PAYMENT.STAFF_ID, values);
    }

    /**
     * Fetch records that have <code>rental_id IN (values)</code>
     */
    public List<net.dualsoft.blockbuster.db.jooq.tables.pojos.Payment> fetchByRentalId(Integer... values) {
        return fetch(Payment.PAYMENT.RENTAL_ID, values);
    }

    /**
     * Fetch records that have <code>amount IN (values)</code>
     */
    public List<net.dualsoft.blockbuster.db.jooq.tables.pojos.Payment> fetchByAmount(BigDecimal... values) {
        return fetch(Payment.PAYMENT.AMOUNT, values);
    }

    /**
     * Fetch records that have <code>payment_date IN (values)</code>
     */
    public List<net.dualsoft.blockbuster.db.jooq.tables.pojos.Payment> fetchByPaymentDate(Timestamp... values) {
        return fetch(Payment.PAYMENT.PAYMENT_DATE, values);
    }

    /**
     * Fetch records that have <code>type IN (values)</code>
     */
    public List<net.dualsoft.blockbuster.db.jooq.tables.pojos.Payment> fetchByType(String... values) {
        return fetch(Payment.PAYMENT.TYPE, values);
    }
}
