/*
 * This file is generated by jOOQ.
 */
package net.dualsoft.blockbuster.db.jooq.tables.daos;


import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import net.dualsoft.blockbuster.db.jooq.enums.RequestStatus;
import net.dualsoft.blockbuster.db.jooq.tables.RentalRequest;
import net.dualsoft.blockbuster.db.jooq.tables.records.RentalRequestRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RentalRequestDao extends DAOImpl<RentalRequestRecord, net.dualsoft.blockbuster.db.jooq.tables.pojos.RentalRequest, Integer> {

    /**
     * Create a new RentalRequestDao without any configuration
     */
    public RentalRequestDao() {
        super(RentalRequest.RENTAL_REQUEST, net.dualsoft.blockbuster.db.jooq.tables.pojos.RentalRequest.class);
    }

    /**
     * Create a new RentalRequestDao with an attached configuration
     */
    public RentalRequestDao(Configuration configuration) {
        super(RentalRequest.RENTAL_REQUEST, net.dualsoft.blockbuster.db.jooq.tables.pojos.RentalRequest.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(net.dualsoft.blockbuster.db.jooq.tables.pojos.RentalRequest object) {
        return object.getRentalRequestId();
    }

    /**
     * Fetch records that have <code>rental_request_id IN (values)</code>
     */
    public List<net.dualsoft.blockbuster.db.jooq.tables.pojos.RentalRequest> fetchByRentalRequestId(Integer... values) {
        return fetch(RentalRequest.RENTAL_REQUEST.RENTAL_REQUEST_ID, values);
    }

    /**
     * Fetch a unique record that has <code>rental_request_id = value</code>
     */
    public net.dualsoft.blockbuster.db.jooq.tables.pojos.RentalRequest fetchOneByRentalRequestId(Integer value) {
        return fetchOne(RentalRequest.RENTAL_REQUEST.RENTAL_REQUEST_ID, value);
    }

    /**
     * Fetch records that have <code>film_id IN (values)</code>
     */
    public List<net.dualsoft.blockbuster.db.jooq.tables.pojos.RentalRequest> fetchByFilmId(Integer... values) {
        return fetch(RentalRequest.RENTAL_REQUEST.FILM_ID, values);
    }

    /**
     * Fetch records that have <code>store_id IN (values)</code>
     */
    public List<net.dualsoft.blockbuster.db.jooq.tables.pojos.RentalRequest> fetchByStoreId(Integer... values) {
        return fetch(RentalRequest.RENTAL_REQUEST.STORE_ID, values);
    }

    /**
     * Fetch records that have <code>customer_id IN (values)</code>
     */
    public List<net.dualsoft.blockbuster.db.jooq.tables.pojos.RentalRequest> fetchByCustomerId(Integer... values) {
        return fetch(RentalRequest.RENTAL_REQUEST.CUSTOMER_ID, values);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<net.dualsoft.blockbuster.db.jooq.tables.pojos.RentalRequest> fetchByStatus(RequestStatus... values) {
        return fetch(RentalRequest.RENTAL_REQUEST.STATUS, values);
    }

    /**
     * Fetch records that have <code>create_date IN (values)</code>
     */
    public List<net.dualsoft.blockbuster.db.jooq.tables.pojos.RentalRequest> fetchByCreateDate(Timestamp... values) {
        return fetch(RentalRequest.RENTAL_REQUEST.CREATE_DATE, values);
    }

    /**
     * Fetch records that have <code>last_update IN (values)</code>
     */
    public List<net.dualsoft.blockbuster.db.jooq.tables.pojos.RentalRequest> fetchByLastUpdate(Timestamp... values) {
        return fetch(RentalRequest.RENTAL_REQUEST.LAST_UPDATE, values);
    }
}
