/*
 * This file is generated by jOOQ.
 */
package net.dualsoft.blockbuster.db.jooq.tables.daos;


import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import net.dualsoft.blockbuster.db.jooq.tables.Rental;
import net.dualsoft.blockbuster.db.jooq.tables.records.RentalRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RentalDao extends DAOImpl<RentalRecord, net.dualsoft.blockbuster.db.jooq.tables.pojos.Rental, Integer> {

    /**
     * Create a new RentalDao without any configuration
     */
    public RentalDao() {
        super(Rental.RENTAL, net.dualsoft.blockbuster.db.jooq.tables.pojos.Rental.class);
    }

    /**
     * Create a new RentalDao with an attached configuration
     */
    public RentalDao(Configuration configuration) {
        super(Rental.RENTAL, net.dualsoft.blockbuster.db.jooq.tables.pojos.Rental.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(net.dualsoft.blockbuster.db.jooq.tables.pojos.Rental object) {
        return object.getRentalId();
    }

    /**
     * Fetch records that have <code>rental_id IN (values)</code>
     */
    public List<net.dualsoft.blockbuster.db.jooq.tables.pojos.Rental> fetchByRentalId(Integer... values) {
        return fetch(Rental.RENTAL.RENTAL_ID, values);
    }

    /**
     * Fetch a unique record that has <code>rental_id = value</code>
     */
    public net.dualsoft.blockbuster.db.jooq.tables.pojos.Rental fetchOneByRentalId(Integer value) {
        return fetchOne(Rental.RENTAL.RENTAL_ID, value);
    }

    /**
     * Fetch records that have <code>rental_date IN (values)</code>
     */
    public List<net.dualsoft.blockbuster.db.jooq.tables.pojos.Rental> fetchByRentalDate(Timestamp... values) {
        return fetch(Rental.RENTAL.RENTAL_DATE, values);
    }

    /**
     * Fetch records that have <code>inventory_id IN (values)</code>
     */
    public List<net.dualsoft.blockbuster.db.jooq.tables.pojos.Rental> fetchByInventoryId(Integer... values) {
        return fetch(Rental.RENTAL.INVENTORY_ID, values);
    }

    /**
     * Fetch records that have <code>customer_id IN (values)</code>
     */
    public List<net.dualsoft.blockbuster.db.jooq.tables.pojos.Rental> fetchByCustomerId(Short... values) {
        return fetch(Rental.RENTAL.CUSTOMER_ID, values);
    }

    /**
     * Fetch records that have <code>return_date IN (values)</code>
     */
    public List<net.dualsoft.blockbuster.db.jooq.tables.pojos.Rental> fetchByReturnDate(Timestamp... values) {
        return fetch(Rental.RENTAL.RETURN_DATE, values);
    }

    /**
     * Fetch records that have <code>staff_id IN (values)</code>
     */
    public List<net.dualsoft.blockbuster.db.jooq.tables.pojos.Rental> fetchByStaffId(Short... values) {
        return fetch(Rental.RENTAL.STAFF_ID, values);
    }

    /**
     * Fetch records that have <code>last_update IN (values)</code>
     */
    public List<net.dualsoft.blockbuster.db.jooq.tables.pojos.Rental> fetchByLastUpdate(Timestamp... values) {
        return fetch(Rental.RENTAL.LAST_UPDATE, values);
    }
}
