/*
 * This file is generated by jOOQ.
 */
package net.dualsoft.blockbuster.db.jooq.tables.daos;


import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import net.dualsoft.blockbuster.db.jooq.tables.Staff;
import net.dualsoft.blockbuster.db.jooq.tables.records.StaffRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StaffDao extends DAOImpl<StaffRecord, net.dualsoft.blockbuster.db.jooq.tables.pojos.Staff, Integer> {

    /**
     * Create a new StaffDao without any configuration
     */
    public StaffDao() {
        super(Staff.STAFF, net.dualsoft.blockbuster.db.jooq.tables.pojos.Staff.class);
    }

    /**
     * Create a new StaffDao with an attached configuration
     */
    public StaffDao(Configuration configuration) {
        super(Staff.STAFF, net.dualsoft.blockbuster.db.jooq.tables.pojos.Staff.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(net.dualsoft.blockbuster.db.jooq.tables.pojos.Staff object) {
        return object.getStaffId();
    }

    /**
     * Fetch records that have <code>staff_id IN (values)</code>
     */
    public List<net.dualsoft.blockbuster.db.jooq.tables.pojos.Staff> fetchByStaffId(Integer... values) {
        return fetch(Staff.STAFF.STAFF_ID, values);
    }

    /**
     * Fetch a unique record that has <code>staff_id = value</code>
     */
    public net.dualsoft.blockbuster.db.jooq.tables.pojos.Staff fetchOneByStaffId(Integer value) {
        return fetchOne(Staff.STAFF.STAFF_ID, value);
    }

    /**
     * Fetch records that have <code>first_name IN (values)</code>
     */
    public List<net.dualsoft.blockbuster.db.jooq.tables.pojos.Staff> fetchByFirstName(String... values) {
        return fetch(Staff.STAFF.FIRST_NAME, values);
    }

    /**
     * Fetch records that have <code>last_name IN (values)</code>
     */
    public List<net.dualsoft.blockbuster.db.jooq.tables.pojos.Staff> fetchByLastName(String... values) {
        return fetch(Staff.STAFF.LAST_NAME, values);
    }

    /**
     * Fetch records that have <code>address_id IN (values)</code>
     */
    public List<net.dualsoft.blockbuster.db.jooq.tables.pojos.Staff> fetchByAddressId(Short... values) {
        return fetch(Staff.STAFF.ADDRESS_ID, values);
    }

    /**
     * Fetch records that have <code>email IN (values)</code>
     */
    public List<net.dualsoft.blockbuster.db.jooq.tables.pojos.Staff> fetchByEmail(String... values) {
        return fetch(Staff.STAFF.EMAIL, values);
    }

    /**
     * Fetch records that have <code>store_id IN (values)</code>
     */
    public List<net.dualsoft.blockbuster.db.jooq.tables.pojos.Staff> fetchByStoreId(Short... values) {
        return fetch(Staff.STAFF.STORE_ID, values);
    }

    /**
     * Fetch records that have <code>active IN (values)</code>
     */
    public List<net.dualsoft.blockbuster.db.jooq.tables.pojos.Staff> fetchByActive(Boolean... values) {
        return fetch(Staff.STAFF.ACTIVE, values);
    }

    /**
     * Fetch records that have <code>username IN (values)</code>
     */
    public List<net.dualsoft.blockbuster.db.jooq.tables.pojos.Staff> fetchByUsername(String... values) {
        return fetch(Staff.STAFF.USERNAME, values);
    }

    /**
     * Fetch records that have <code>password IN (values)</code>
     */
    public List<net.dualsoft.blockbuster.db.jooq.tables.pojos.Staff> fetchByPassword(String... values) {
        return fetch(Staff.STAFF.PASSWORD, values);
    }

    /**
     * Fetch records that have <code>last_update IN (values)</code>
     */
    public List<net.dualsoft.blockbuster.db.jooq.tables.pojos.Staff> fetchByLastUpdate(Timestamp... values) {
        return fetch(Staff.STAFF.LAST_UPDATE, values);
    }

    /**
     * Fetch records that have <code>picture IN (values)</code>
     */
    public List<net.dualsoft.blockbuster.db.jooq.tables.pojos.Staff> fetchByPicture(String... values) {
        return fetch(Staff.STAFF.PICTURE, values);
    }
}
