/*
 * This file is generated by jOOQ.
 */
package net.dualsoft.blockbuster.db.jooq;


import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import net.dualsoft.blockbuster.db.jooq.routines.GetCustomerBalance;
import net.dualsoft.blockbuster.db.jooq.routines.GroupConcat;
import net.dualsoft.blockbuster.db.jooq.routines.InventoryHeldByCustomer;
import net.dualsoft.blockbuster.db.jooq.routines.InventoryInStock;
import net.dualsoft.blockbuster.db.jooq.routines.LastDay;
import net.dualsoft.blockbuster.db.jooq.routines._GroupConcat;
import net.dualsoft.blockbuster.db.jooq.tables.FilmInStock;
import net.dualsoft.blockbuster.db.jooq.tables.FilmNotInStock;
import net.dualsoft.blockbuster.db.jooq.tables.RewardsReport;
import net.dualsoft.blockbuster.db.jooq.tables.records.FilmInStockRecord;
import net.dualsoft.blockbuster.db.jooq.tables.records.FilmNotInStockRecord;
import net.dualsoft.blockbuster.db.jooq.tables.records.RewardsReportRecord;

import org.jooq.AggregateFunction;
import org.jooq.Configuration;
import org.jooq.Field;
import org.jooq.Result;


/**
 * Convenience access to all stored procedures and functions in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Routines {

    /**
     * Call <code>get_customer_balance</code>
     */
    public static BigDecimal getCustomerBalance(Configuration configuration, Integer pCustomerId, Timestamp pEffectiveDate) {
        GetCustomerBalance f = new GetCustomerBalance();
        f.setPCustomerId(pCustomerId);
        f.setPEffectiveDate(pEffectiveDate);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>get_customer_balance</code> as a field.
     */
    public static Field<BigDecimal> getCustomerBalance(Integer pCustomerId, Timestamp pEffectiveDate) {
        GetCustomerBalance f = new GetCustomerBalance();
        f.setPCustomerId(pCustomerId);
        f.setPEffectiveDate(pEffectiveDate);

        return f.asField();
    }

    /**
     * Get <code>get_customer_balance</code> as a field.
     */
    public static Field<BigDecimal> getCustomerBalance(Field<Integer> pCustomerId, Field<Timestamp> pEffectiveDate) {
        GetCustomerBalance f = new GetCustomerBalance();
        f.setPCustomerId(pCustomerId);
        f.setPEffectiveDate(pEffectiveDate);

        return f.asField();
    }

    /**
     * Call <code>_group_concat</code>
     */
    public static String _GroupConcat(Configuration configuration, String __1, String __2) {
        _GroupConcat f = new _GroupConcat();
        f.set__1(__1);
        f.set__2(__2);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>_group_concat</code> as a field.
     */
    public static Field<String> _GroupConcat(String __1, String __2) {
        _GroupConcat f = new _GroupConcat();
        f.set__1(__1);
        f.set__2(__2);

        return f.asField();
    }

    /**
     * Get <code>_group_concat</code> as a field.
     */
    public static Field<String> _GroupConcat(Field<String> __1, Field<String> __2) {
        _GroupConcat f = new _GroupConcat();
        f.set__1(__1);
        f.set__2(__2);

        return f.asField();
    }

    /**
     * Get <code>group_concat</code> as a field.
     */
    public static AggregateFunction<String> groupConcat(String __1) {
        GroupConcat f = new GroupConcat();
        f.set__1(__1);

        return f.asAggregateFunction();
    }

    /**
     * Get <code>group_concat</code> as a field.
     */
    public static AggregateFunction<String> groupConcat(Field<String> __1) {
        GroupConcat f = new GroupConcat();
        f.set__1(__1);

        return f.asAggregateFunction();
    }

    /**
     * Call <code>inventory_held_by_customer</code>
     */
    public static Integer inventoryHeldByCustomer(Configuration configuration, Integer pInventoryId) {
        InventoryHeldByCustomer f = new InventoryHeldByCustomer();
        f.setPInventoryId(pInventoryId);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>inventory_held_by_customer</code> as a field.
     */
    public static Field<Integer> inventoryHeldByCustomer(Integer pInventoryId) {
        InventoryHeldByCustomer f = new InventoryHeldByCustomer();
        f.setPInventoryId(pInventoryId);

        return f.asField();
    }

    /**
     * Get <code>inventory_held_by_customer</code> as a field.
     */
    public static Field<Integer> inventoryHeldByCustomer(Field<Integer> pInventoryId) {
        InventoryHeldByCustomer f = new InventoryHeldByCustomer();
        f.setPInventoryId(pInventoryId);

        return f.asField();
    }

    /**
     * Call <code>inventory_in_stock</code>
     */
    public static Boolean inventoryInStock(Configuration configuration, Integer pInventoryId) {
        InventoryInStock f = new InventoryInStock();
        f.setPInventoryId(pInventoryId);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>inventory_in_stock</code> as a field.
     */
    public static Field<Boolean> inventoryInStock(Integer pInventoryId) {
        InventoryInStock f = new InventoryInStock();
        f.setPInventoryId(pInventoryId);

        return f.asField();
    }

    /**
     * Get <code>inventory_in_stock</code> as a field.
     */
    public static Field<Boolean> inventoryInStock(Field<Integer> pInventoryId) {
        InventoryInStock f = new InventoryInStock();
        f.setPInventoryId(pInventoryId);

        return f.asField();
    }

    /**
     * Call <code>last_day</code>
     */
    public static Timestamp lastDay(Configuration configuration, Timestamp __1) {
        LastDay f = new LastDay();
        f.set__1(__1);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>last_day</code> as a field.
     */
    public static Field<Timestamp> lastDay(Timestamp __1) {
        LastDay f = new LastDay();
        f.set__1(__1);

        return f.asField();
    }

    /**
     * Get <code>last_day</code> as a field.
     */
    public static Field<Timestamp> lastDay(Field<Timestamp> __1) {
        LastDay f = new LastDay();
        f.set__1(__1);

        return f.asField();
    }

    /**
     * Call <code>film_in_stock</code>.
     */
    public static Result<FilmInStockRecord> filmInStock(Configuration configuration, Integer pFilmId, Integer pStoreId) {
        return configuration.dsl().selectFrom(net.dualsoft.blockbuster.db.jooq.tables.FilmInStock.FILM_IN_STOCK.call(pFilmId, pStoreId)).fetch();
    }

    /**
     * Get <code>film_in_stock</code> as a table.
     */
    public static FilmInStock filmInStock(Integer pFilmId, Integer pStoreId) {
        return net.dualsoft.blockbuster.db.jooq.tables.FilmInStock.FILM_IN_STOCK.call(pFilmId, pStoreId);
    }

    /**
     * Get <code>film_in_stock</code> as a table.
     */
    public static FilmInStock filmInStock(Field<Integer> pFilmId, Field<Integer> pStoreId) {
        return net.dualsoft.blockbuster.db.jooq.tables.FilmInStock.FILM_IN_STOCK.call(pFilmId, pStoreId);
    }

    /**
     * Call <code>film_not_in_stock</code>.
     */
    public static Result<FilmNotInStockRecord> filmNotInStock(Configuration configuration, Integer pFilmId, Integer pStoreId) {
        return configuration.dsl().selectFrom(net.dualsoft.blockbuster.db.jooq.tables.FilmNotInStock.FILM_NOT_IN_STOCK.call(pFilmId, pStoreId)).fetch();
    }

    /**
     * Get <code>film_not_in_stock</code> as a table.
     */
    public static FilmNotInStock filmNotInStock(Integer pFilmId, Integer pStoreId) {
        return net.dualsoft.blockbuster.db.jooq.tables.FilmNotInStock.FILM_NOT_IN_STOCK.call(pFilmId, pStoreId);
    }

    /**
     * Get <code>film_not_in_stock</code> as a table.
     */
    public static FilmNotInStock filmNotInStock(Field<Integer> pFilmId, Field<Integer> pStoreId) {
        return net.dualsoft.blockbuster.db.jooq.tables.FilmNotInStock.FILM_NOT_IN_STOCK.call(pFilmId, pStoreId);
    }

    /**
     * Call <code>rewards_report</code>.
     */
    public static Result<RewardsReportRecord> rewardsReport(Configuration configuration, Integer minMonthlyPurchases, BigDecimal minDollarAmountPurchased) {
        return configuration.dsl().selectFrom(net.dualsoft.blockbuster.db.jooq.tables.RewardsReport.REWARDS_REPORT.call(minMonthlyPurchases, minDollarAmountPurchased)).fetch();
    }

    /**
     * Get <code>rewards_report</code> as a table.
     */
    public static RewardsReport rewardsReport(Integer minMonthlyPurchases, BigDecimal minDollarAmountPurchased) {
        return net.dualsoft.blockbuster.db.jooq.tables.RewardsReport.REWARDS_REPORT.call(minMonthlyPurchases, minDollarAmountPurchased);
    }

    /**
     * Get <code>rewards_report</code> as a table.
     */
    public static RewardsReport rewardsReport(Field<Integer> minMonthlyPurchases, Field<BigDecimal> minDollarAmountPurchased) {
        return net.dualsoft.blockbuster.db.jooq.tables.RewardsReport.REWARDS_REPORT.call(minMonthlyPurchases, minDollarAmountPurchased);
    }
}
