/*
 * This file is generated by jOOQ.
 */
package net.dualsoft.blockbuster.db.jooq.tables.interfaces;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IActor extends Serializable {

    /**
     * Setter for <code>actor.actor_id</code>.
     */
    public void setActorId(Integer value);

    /**
     * Getter for <code>actor.actor_id</code>.
     */
    public Integer getActorId();

    /**
     * Setter for <code>actor.name</code>.
     */
    public void setName(String value);

    /**
     * Getter for <code>actor.name</code>.
     */
    public String getName();

    /**
     * Setter for <code>actor.last_update</code>.
     */
    public void setLastUpdate(Timestamp value);

    /**
     * Getter for <code>actor.last_update</code>.
     */
    public Timestamp getLastUpdate();

    /**
     * Setter for <code>actor.picture_url</code>.
     */
    public void setPictureUrl(String value);

    /**
     * Getter for <code>actor.picture_url</code>.
     */
    public String getPictureUrl();

    /**
     * Setter for <code>actor.biography</code>.
     */
    public void setBiography(String value);

    /**
     * Getter for <code>actor.biography</code>.
     */
    public String getBiography();

    /**
     * Setter for <code>actor.moviedb_id</code>.
     */
    public void setMoviedbId(Integer value);

    /**
     * Getter for <code>actor.moviedb_id</code>.
     */
    public Integer getMoviedbId();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IActor
     */
    public void from(net.dualsoft.blockbuster.db.jooq.tables.interfaces.IActor from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IActor
     */
    public <E extends net.dualsoft.blockbuster.db.jooq.tables.interfaces.IActor> E into(E into);
}
