/*
 * This file is generated by jOOQ.
 */
package net.dualsoft.blockbuster.db.jooq.tables.interfaces;


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IAddress extends Serializable {

    /**
     * Setter for <code>address.address_id</code>.
     */
    public void setAddressId(Integer value);

    /**
     * Getter for <code>address.address_id</code>.
     */
    public Integer getAddressId();

    /**
     * Setter for <code>address.address</code>.
     */
    public void setAddress(String value);

    /**
     * Getter for <code>address.address</code>.
     */
    public String getAddress();

    /**
     * Setter for <code>address.district</code>.
     */
    public void setDistrict(String value);

    /**
     * Getter for <code>address.district</code>.
     */
    public String getDistrict();

    /**
     * Setter for <code>address.city_id</code>.
     */
    public void setCityId(Short value);

    /**
     * Getter for <code>address.city_id</code>.
     */
    public Short getCityId();

    /**
     * Setter for <code>address.postal_code</code>.
     */
    public void setPostalCode(String value);

    /**
     * Getter for <code>address.postal_code</code>.
     */
    public String getPostalCode();

    /**
     * Setter for <code>address.last_update</code>.
     */
    public void setLastUpdate(Timestamp value);

    /**
     * Getter for <code>address.last_update</code>.
     */
    public Timestamp getLastUpdate();

    /**
     * Setter for <code>address.longitude</code>.
     */
    public void setLongitude(BigDecimal value);

    /**
     * Getter for <code>address.longitude</code>.
     */
    public BigDecimal getLongitude();

    /**
     * Setter for <code>address.latitude</code>.
     */
    public void setLatitude(BigDecimal value);

    /**
     * Getter for <code>address.latitude</code>.
     */
    public BigDecimal getLatitude();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IAddress
     */
    public void from(net.dualsoft.blockbuster.db.jooq.tables.interfaces.IAddress from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IAddress
     */
    public <E extends net.dualsoft.blockbuster.db.jooq.tables.interfaces.IAddress> E into(E into);
}
