/*
 * This file is generated by jOOQ.
 */
package net.dualsoft.blockbuster.db.jooq.tables.interfaces;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ICategory extends Serializable {

    /**
     * Setter for <code>category.category_id</code>.
     */
    public void setCategoryId(Integer value);

    /**
     * Getter for <code>category.category_id</code>.
     */
    public Integer getCategoryId();

    /**
     * Setter for <code>category.name</code>.
     */
    public void setName(String value);

    /**
     * Getter for <code>category.name</code>.
     */
    public String getName();

    /**
     * Setter for <code>category.last_update</code>.
     */
    public void setLastUpdate(Timestamp value);

    /**
     * Getter for <code>category.last_update</code>.
     */
    public Timestamp getLastUpdate();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ICategory
     */
    public void from(net.dualsoft.blockbuster.db.jooq.tables.interfaces.ICategory from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ICategory
     */
    public <E extends net.dualsoft.blockbuster.db.jooq.tables.interfaces.ICategory> E into(E into);
}
