/*
 * This file is generated by jOOQ.
 */
package net.dualsoft.blockbuster.db.jooq.tables.interfaces;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ICity extends Serializable {

    /**
     * Setter for <code>city.city_id</code>.
     */
    public void setCityId(Integer value);

    /**
     * Getter for <code>city.city_id</code>.
     */
    public Integer getCityId();

    /**
     * Setter for <code>city.city</code>.
     */
    public void setCity(String value);

    /**
     * Getter for <code>city.city</code>.
     */
    public String getCity();

    /**
     * Setter for <code>city.country_id</code>.
     */
    public void setCountryId(Short value);

    /**
     * Getter for <code>city.country_id</code>.
     */
    public Short getCountryId();

    /**
     * Setter for <code>city.last_update</code>.
     */
    public void setLastUpdate(Timestamp value);

    /**
     * Getter for <code>city.last_update</code>.
     */
    public Timestamp getLastUpdate();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ICity
     */
    public void from(net.dualsoft.blockbuster.db.jooq.tables.interfaces.ICity from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ICity
     */
    public <E extends net.dualsoft.blockbuster.db.jooq.tables.interfaces.ICity> E into(E into);
}
