/*
 * This file is generated by jOOQ.
 */
package net.dualsoft.blockbuster.db.jooq.tables.interfaces;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ICountry extends Serializable {

    /**
     * Setter for <code>country.country_id</code>.
     */
    public void setCountryId(Integer value);

    /**
     * Getter for <code>country.country_id</code>.
     */
    public Integer getCountryId();

    /**
     * Setter for <code>country.country</code>.
     */
    public void setCountry(String value);

    /**
     * Getter for <code>country.country</code>.
     */
    public String getCountry();

    /**
     * Setter for <code>country.last_update</code>.
     */
    public void setLastUpdate(Timestamp value);

    /**
     * Getter for <code>country.last_update</code>.
     */
    public Timestamp getLastUpdate();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ICountry
     */
    public void from(net.dualsoft.blockbuster.db.jooq.tables.interfaces.ICountry from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ICountry
     */
    public <E extends net.dualsoft.blockbuster.db.jooq.tables.interfaces.ICountry> E into(E into);
}
