/*
 * This file is generated by jOOQ.
 */
package net.dualsoft.blockbuster.db.jooq.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IFilmNotInStock extends Serializable {

    /**
     * Setter for <code>film_not_in_stock.p_film_count</code>.
     */
    public void setPFilmCount(Integer value);

    /**
     * Getter for <code>film_not_in_stock.p_film_count</code>.
     */
    public Integer getPFilmCount();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IFilmNotInStock
     */
    public void from(net.dualsoft.blockbuster.db.jooq.tables.interfaces.IFilmNotInStock from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IFilmNotInStock
     */
    public <E extends net.dualsoft.blockbuster.db.jooq.tables.interfaces.IFilmNotInStock> E into(E into);
}
