/*
 * This file is generated by jOOQ.
 */
package net.dualsoft.blockbuster.db.jooq.tables.interfaces;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IFilmActor extends Serializable {

    /**
     * Setter for <code>film_actor.actor_id</code>.
     */
    public void setActorId(Short value);

    /**
     * Getter for <code>film_actor.actor_id</code>.
     */
    public Short getActorId();

    /**
     * Setter for <code>film_actor.film_id</code>.
     */
    public void setFilmId(Short value);

    /**
     * Getter for <code>film_actor.film_id</code>.
     */
    public Short getFilmId();

    /**
     * Setter for <code>film_actor.last_update</code>.
     */
    public void setLastUpdate(Timestamp value);

    /**
     * Getter for <code>film_actor.last_update</code>.
     */
    public Timestamp getLastUpdate();

    /**
     * Setter for <code>film_actor.character</code>.
     */
    public void setCharacter(String value);

    /**
     * Getter for <code>film_actor.character</code>.
     */
    public String getCharacter();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IFilmActor
     */
    public void from(net.dualsoft.blockbuster.db.jooq.tables.interfaces.IFilmActor from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IFilmActor
     */
    public <E extends net.dualsoft.blockbuster.db.jooq.tables.interfaces.IFilmActor> E into(E into);
}
