/*
 * This file is generated by jOOQ.
 */
package net.dualsoft.blockbuster.db.jooq.tables.interfaces;


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import net.dualsoft.blockbuster.db.jooq.enums.MpaaRating;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IFilm extends Serializable {

    /**
     * Setter for <code>film.film_id</code>.
     */
    public void setFilmId(Integer value);

    /**
     * Getter for <code>film.film_id</code>.
     */
    public Integer getFilmId();

    /**
     * Setter for <code>film.title</code>.
     */
    public void setTitle(String value);

    /**
     * Getter for <code>film.title</code>.
     */
    public String getTitle();

    /**
     * Setter for <code>film.description</code>.
     */
    public void setDescription(String value);

    /**
     * Getter for <code>film.description</code>.
     */
    public String getDescription();

    /**
     * Setter for <code>film.release_year</code>.
     */
    public void setReleaseYear(Integer value);

    /**
     * Getter for <code>film.release_year</code>.
     */
    public Integer getReleaseYear();

    /**
     * Setter for <code>film.language_id</code>.
     */
    public void setLanguageId(Short value);

    /**
     * Getter for <code>film.language_id</code>.
     */
    public Short getLanguageId();

    /**
     * Setter for <code>film.rental_duration</code>.
     */
    public void setRentalDuration(Short value);

    /**
     * Getter for <code>film.rental_duration</code>.
     */
    public Short getRentalDuration();

    /**
     * Setter for <code>film.rental_rate</code>.
     */
    public void setRentalRate(BigDecimal value);

    /**
     * Getter for <code>film.rental_rate</code>.
     */
    public BigDecimal getRentalRate();

    /**
     * Setter for <code>film.length</code>.
     */
    public void setLength(Short value);

    /**
     * Getter for <code>film.length</code>.
     */
    public Short getLength();

    /**
     * Setter for <code>film.replacement_cost</code>.
     */
    public void setReplacementCost(BigDecimal value);

    /**
     * Getter for <code>film.replacement_cost</code>.
     */
    public BigDecimal getReplacementCost();

    /**
     * Setter for <code>film.rating</code>.
     */
    public void setRating(MpaaRating value);

    /**
     * Getter for <code>film.rating</code>.
     */
    public MpaaRating getRating();

    /**
     * Setter for <code>film.last_update</code>.
     */
    public void setLastUpdate(Timestamp value);

    /**
     * Getter for <code>film.last_update</code>.
     */
    public Timestamp getLastUpdate();

    /**
     * Setter for <code>film.special_features</code>.
     */
    public void setSpecialFeatures(String... value);

    /**
     * Getter for <code>film.special_features</code>.
     */
    public String[] getSpecialFeatures();

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public void setFulltext(Object value);

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public Object getFulltext();

    /**
     * Setter for <code>film.poster_url</code>.
     */
    public void setPosterUrl(String value);

    /**
     * Getter for <code>film.poster_url</code>.
     */
    public String getPosterUrl();

    /**
     * Setter for <code>film.star_rating</code>.
     */
    public void setStarRating(BigDecimal value);

    /**
     * Getter for <code>film.star_rating</code>.
     */
    public BigDecimal getStarRating();

    /**
     * Setter for <code>film.moviedb_id</code>.
     */
    public void setMoviedbId(Integer value);

    /**
     * Getter for <code>film.moviedb_id</code>.
     */
    public Integer getMoviedbId();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IFilm
     */
    public void from(net.dualsoft.blockbuster.db.jooq.tables.interfaces.IFilm from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IFilm
     */
    public <E extends net.dualsoft.blockbuster.db.jooq.tables.interfaces.IFilm> E into(E into);
}
