/*
 * This file is generated by jOOQ.
 */
package net.dualsoft.blockbuster.db.jooq.tables.interfaces;


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IPayment extends Serializable {

    /**
     * Setter for <code>payment.payment_id</code>.
     */
    public void setPaymentId(Integer value);

    /**
     * Getter for <code>payment.payment_id</code>.
     */
    public Integer getPaymentId();

    /**
     * Setter for <code>payment.customer_id</code>.
     */
    public void setCustomerId(Short value);

    /**
     * Getter for <code>payment.customer_id</code>.
     */
    public Short getCustomerId();

    /**
     * Setter for <code>payment.staff_id</code>.
     */
    public void setStaffId(Short value);

    /**
     * Getter for <code>payment.staff_id</code>.
     */
    public Short getStaffId();

    /**
     * Setter for <code>payment.rental_id</code>.
     */
    public void setRentalId(Integer value);

    /**
     * Getter for <code>payment.rental_id</code>.
     */
    public Integer getRentalId();

    /**
     * Setter for <code>payment.amount</code>.
     */
    public void setAmount(BigDecimal value);

    /**
     * Getter for <code>payment.amount</code>.
     */
    public BigDecimal getAmount();

    /**
     * Setter for <code>payment.payment_date</code>.
     */
    public void setPaymentDate(Timestamp value);

    /**
     * Getter for <code>payment.payment_date</code>.
     */
    public Timestamp getPaymentDate();

    /**
     * Setter for <code>payment.type</code>.
     */
    public void setType(String value);

    /**
     * Getter for <code>payment.type</code>.
     */
    public String getType();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IPayment
     */
    public void from(net.dualsoft.blockbuster.db.jooq.tables.interfaces.IPayment from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IPayment
     */
    public <E extends net.dualsoft.blockbuster.db.jooq.tables.interfaces.IPayment> E into(E into);
}
