/*
 * This file is generated by jOOQ.
 */
package net.dualsoft.blockbuster.db.jooq.tables.interfaces;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IRental extends Serializable {

    /**
     * Setter for <code>rental.rental_id</code>.
     */
    public void setRentalId(Integer value);

    /**
     * Getter for <code>rental.rental_id</code>.
     */
    public Integer getRentalId();

    /**
     * Setter for <code>rental.rental_date</code>.
     */
    public void setRentalDate(Timestamp value);

    /**
     * Getter for <code>rental.rental_date</code>.
     */
    public Timestamp getRentalDate();

    /**
     * Setter for <code>rental.inventory_id</code>.
     */
    public void setInventoryId(Integer value);

    /**
     * Getter for <code>rental.inventory_id</code>.
     */
    public Integer getInventoryId();

    /**
     * Setter for <code>rental.customer_id</code>.
     */
    public void setCustomerId(Short value);

    /**
     * Getter for <code>rental.customer_id</code>.
     */
    public Short getCustomerId();

    /**
     * Setter for <code>rental.return_date</code>.
     */
    public void setReturnDate(Timestamp value);

    /**
     * Getter for <code>rental.return_date</code>.
     */
    public Timestamp getReturnDate();

    /**
     * Setter for <code>rental.staff_id</code>.
     */
    public void setStaffId(Short value);

    /**
     * Getter for <code>rental.staff_id</code>.
     */
    public Short getStaffId();

    /**
     * Setter for <code>rental.last_update</code>.
     */
    public void setLastUpdate(Timestamp value);

    /**
     * Getter for <code>rental.last_update</code>.
     */
    public Timestamp getLastUpdate();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IRental
     */
    public void from(net.dualsoft.blockbuster.db.jooq.tables.interfaces.IRental from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IRental
     */
    public <E extends net.dualsoft.blockbuster.db.jooq.tables.interfaces.IRental> E into(E into);
}
