/*
 * This file is generated by jOOQ.
 */
package net.dualsoft.blockbuster.db.jooq.tables.interfaces;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;

import net.dualsoft.blockbuster.db.jooq.enums.RequestStatus;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IRentalRequest extends Serializable {

    /**
     * Setter for <code>rental_request.rental_request_id</code>.
     */
    public void setRentalRequestId(Integer value);

    /**
     * Getter for <code>rental_request.rental_request_id</code>.
     */
    public Integer getRentalRequestId();

    /**
     * Setter for <code>rental_request.film_id</code>.
     */
    public void setFilmId(Integer value);

    /**
     * Getter for <code>rental_request.film_id</code>.
     */
    public Integer getFilmId();

    /**
     * Setter for <code>rental_request.store_id</code>.
     */
    public void setStoreId(Integer value);

    /**
     * Getter for <code>rental_request.store_id</code>.
     */
    public Integer getStoreId();

    /**
     * Setter for <code>rental_request.customer_id</code>.
     */
    public void setCustomerId(Integer value);

    /**
     * Getter for <code>rental_request.customer_id</code>.
     */
    public Integer getCustomerId();

    /**
     * Setter for <code>rental_request.status</code>.
     */
    public void setStatus(RequestStatus value);

    /**
     * Getter for <code>rental_request.status</code>.
     */
    public RequestStatus getStatus();

    /**
     * Setter for <code>rental_request.create_date</code>.
     */
    public void setCreateDate(Timestamp value);

    /**
     * Getter for <code>rental_request.create_date</code>.
     */
    public Timestamp getCreateDate();

    /**
     * Setter for <code>rental_request.last_update</code>.
     */
    public void setLastUpdate(Timestamp value);

    /**
     * Getter for <code>rental_request.last_update</code>.
     */
    public Timestamp getLastUpdate();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IRentalRequest
     */
    public void from(net.dualsoft.blockbuster.db.jooq.tables.interfaces.IRentalRequest from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IRentalRequest
     */
    public <E extends net.dualsoft.blockbuster.db.jooq.tables.interfaces.IRentalRequest> E into(E into);
}
