/*
 * This file is generated by jOOQ.
 */
package net.dualsoft.blockbuster.db.jooq.tables.interfaces;


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IRewardsReport extends Serializable {

    /**
     * Setter for <code>rewards_report.customer_id</code>.
     */
    public void setCustomerId(Integer value);

    /**
     * Getter for <code>rewards_report.customer_id</code>.
     */
    public Integer getCustomerId();

    /**
     * Setter for <code>rewards_report.store_id</code>.
     */
    public void setStoreId(Short value);

    /**
     * Getter for <code>rewards_report.store_id</code>.
     */
    public Short getStoreId();

    /**
     * Setter for <code>rewards_report.first_name</code>.
     */
    public void setFirstName(String value);

    /**
     * Getter for <code>rewards_report.first_name</code>.
     */
    public String getFirstName();

    /**
     * Setter for <code>rewards_report.last_name</code>.
     */
    public void setLastName(String value);

    /**
     * Getter for <code>rewards_report.last_name</code>.
     */
    public String getLastName();

    /**
     * Setter for <code>rewards_report.email</code>.
     */
    public void setEmail(String value);

    /**
     * Getter for <code>rewards_report.email</code>.
     */
    public String getEmail();

    /**
     * Setter for <code>rewards_report.address_id</code>.
     */
    public void setAddressId(Short value);

    /**
     * Getter for <code>rewards_report.address_id</code>.
     */
    public Short getAddressId();

    /**
     * Setter for <code>rewards_report.activebool</code>.
     */
    public void setActivebool(Boolean value);

    /**
     * Getter for <code>rewards_report.activebool</code>.
     */
    public Boolean getActivebool();

    /**
     * Setter for <code>rewards_report.create_date</code>.
     */
    public void setCreateDate(Timestamp value);

    /**
     * Getter for <code>rewards_report.create_date</code>.
     */
    public Timestamp getCreateDate();

    /**
     * Setter for <code>rewards_report.last_update</code>.
     */
    public void setLastUpdate(Timestamp value);

    /**
     * Getter for <code>rewards_report.last_update</code>.
     */
    public Timestamp getLastUpdate();

    /**
     * Setter for <code>rewards_report.active</code>.
     */
    public void setActive(Integer value);

    /**
     * Getter for <code>rewards_report.active</code>.
     */
    public Integer getActive();

    /**
     * Setter for <code>rewards_report.password</code>.
     */
    public void setPassword(String value);

    /**
     * Getter for <code>rewards_report.password</code>.
     */
    public String getPassword();

    /**
     * Setter for <code>rewards_report.balance</code>.
     */
    public void setBalance(BigDecimal value);

    /**
     * Getter for <code>rewards_report.balance</code>.
     */
    public BigDecimal getBalance();

    /**
     * Setter for <code>rewards_report.avatar_url</code>.
     */
    public void setAvatarUrl(String value);

    /**
     * Getter for <code>rewards_report.avatar_url</code>.
     */
    public String getAvatarUrl();

    /**
     * Setter for <code>rewards_report.username</code>.
     */
    public void setUsername(String value);

    /**
     * Getter for <code>rewards_report.username</code>.
     */
    public String getUsername();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IRewardsReport
     */
    public void from(net.dualsoft.blockbuster.db.jooq.tables.interfaces.IRewardsReport from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IRewardsReport
     */
    public <E extends net.dualsoft.blockbuster.db.jooq.tables.interfaces.IRewardsReport> E into(E into);
}
