/*
 * This file is generated by jOOQ.
 */
package net.dualsoft.blockbuster.db.jooq.tables.interfaces;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IStore extends Serializable {

    /**
     * Setter for <code>store.store_id</code>.
     */
    public void setStoreId(Integer value);

    /**
     * Getter for <code>store.store_id</code>.
     */
    public Integer getStoreId();

    /**
     * Setter for <code>store.manager_staff_id</code>.
     */
    public void setManagerStaffId(Short value);

    /**
     * Getter for <code>store.manager_staff_id</code>.
     */
    public Short getManagerStaffId();

    /**
     * Setter for <code>store.address_id</code>.
     */
    public void setAddressId(Short value);

    /**
     * Getter for <code>store.address_id</code>.
     */
    public Short getAddressId();

    /**
     * Setter for <code>store.last_update</code>.
     */
    public void setLastUpdate(Timestamp value);

    /**
     * Getter for <code>store.last_update</code>.
     */
    public Timestamp getLastUpdate();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IStore
     */
    public void from(net.dualsoft.blockbuster.db.jooq.tables.interfaces.IStore from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IStore
     */
    public <E extends net.dualsoft.blockbuster.db.jooq.tables.interfaces.IStore> E into(E into);
}
