/*
 * This file is generated by jOOQ.
 */
package net.dualsoft.blockbuster.db.jooq.tables.interfaces;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IUserNotification extends Serializable {

    /**
     * Setter for <code>user_notification.user_notification_id</code>.
     */
    public void setUserNotificationId(Integer value);

    /**
     * Getter for <code>user_notification.user_notification_id</code>.
     */
    public Integer getUserNotificationId();

    /**
     * Setter for <code>user_notification.customer_id</code>.
     */
    public void setCustomerId(Integer value);

    /**
     * Getter for <code>user_notification.customer_id</code>.
     */
    public Integer getCustomerId();

    /**
     * Setter for <code>user_notification.title</code>.
     */
    public void setTitle(String value);

    /**
     * Getter for <code>user_notification.title</code>.
     */
    public String getTitle();

    /**
     * Setter for <code>user_notification.notification_text</code>.
     */
    public void setNotificationText(String value);

    /**
     * Getter for <code>user_notification.notification_text</code>.
     */
    public String getNotificationText();

    /**
     * Setter for <code>user_notification.read</code>.
     */
    public void setRead(Boolean value);

    /**
     * Getter for <code>user_notification.read</code>.
     */
    public Boolean getRead();

    /**
     * Setter for <code>user_notification.last_update</code>.
     */
    public void setLastUpdate(Timestamp value);

    /**
     * Getter for <code>user_notification.last_update</code>.
     */
    public Timestamp getLastUpdate();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IUserNotification
     */
    public void from(net.dualsoft.blockbuster.db.jooq.tables.interfaces.IUserNotification from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IUserNotification
     */
    public <E extends net.dualsoft.blockbuster.db.jooq.tables.interfaces.IUserNotification> E into(E into);
}
