/*
 * This file is generated by jOOQ.
 */
package net.dualsoft.blockbuster.db.jooq.routines;


import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import net.dualsoft.blockbuster.db.jooq.DefaultSchema;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GetCustomerBalance extends AbstractRoutine<BigDecimal> {

    private static final long serialVersionUID = -821270871;

    /**
     * The parameter <code>get_customer_balance.RETURN_VALUE</code>.
     */
    public static final Parameter<BigDecimal> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.NUMERIC, false, false);

    /**
     * The parameter <code>get_customer_balance.p_customer_id</code>.
     */
    public static final Parameter<Integer> P_CUSTOMER_ID = Internal.createParameter("p_customer_id", org.jooq.impl.SQLDataType.INTEGER, false, false);

    /**
     * The parameter <code>get_customer_balance.p_effective_date</code>.
     */
    public static final Parameter<Timestamp> P_EFFECTIVE_DATE = Internal.createParameter("p_effective_date", org.jooq.impl.SQLDataType.TIMESTAMP, false, false);

    /**
     * Create a new routine call instance
     */
    public GetCustomerBalance() {
        super("get_customer_balance", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.NUMERIC);

        setReturnParameter(RETURN_VALUE);
        addInParameter(P_CUSTOMER_ID);
        addInParameter(P_EFFECTIVE_DATE);
    }

    /**
     * Set the <code>p_customer_id</code> parameter IN value to the routine
     */
    public void setPCustomerId(Integer value) {
        setValue(P_CUSTOMER_ID, value);
    }

    /**
     * Set the <code>p_customer_id</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void setPCustomerId(Field<Integer> field) {
        setField(P_CUSTOMER_ID, field);
    }

    /**
     * Set the <code>p_effective_date</code> parameter IN value to the routine
     */
    public void setPEffectiveDate(Timestamp value) {
        setValue(P_EFFECTIVE_DATE, value);
    }

    /**
     * Set the <code>p_effective_date</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void setPEffectiveDate(Field<Timestamp> field) {
        setField(P_EFFECTIVE_DATE, field);
    }
}
