/*
 * This file is generated by jOOQ.
 */
package net.dualsoft.blockbuster.db.jooq.routines;


import java.sql.Timestamp;

import javax.annotation.Generated;

import net.dualsoft.blockbuster.db.jooq.DefaultSchema;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.DateAsTimestampBinding;
import org.jooq.impl.Internal;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LastDay extends AbstractRoutine<Timestamp> {

    private static final long serialVersionUID = 2023978365;

    /**
     * The parameter <code>last_day.RETURN_VALUE</code>.
     */
    public static final Parameter<Timestamp> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.TIMESTAMP, false, false, new DateAsTimestampBinding());

    /**
     * The parameter <code>last_day._1</code>.
     */
    public static final Parameter<Timestamp> _1 = Internal.createParameter("_1", org.jooq.impl.SQLDataType.TIMESTAMP, false, true);

    /**
     * Create a new routine call instance
     */
    public LastDay() {
        super("last_day", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.TIMESTAMP, new DateAsTimestampBinding());

        setReturnParameter(RETURN_VALUE);
        addInParameter(_1);
    }

    /**
     * Set the <code>_1</code> parameter IN value to the routine
     */
    public void set__1(Timestamp value) {
        setValue(_1, value);
    }

    /**
     * Set the <code>_1</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void set__1(Field<Timestamp> field) {
        setField(_1, field);
    }
}
