/*
 * This file is generated by jOOQ.
 */
package net.dualsoft.blockbuster.db.jooq.domains;


import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
// ((VALUE >= 1901) AND (VALUE <= 2155))
public class Year {
}
