/*
 * This file is generated by jOOQ.
 */
package net.dualsoft.blockbuster.db.jooq.tables;


import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import net.dualsoft.blockbuster.db.jooq.DefaultSchema;
import net.dualsoft.blockbuster.db.jooq.Keys;
import net.dualsoft.blockbuster.db.jooq.tables.records.RewardsReportRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.DateAsTimestampBinding;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RewardsReport extends TableImpl<RewardsReportRecord> {

    private static final long serialVersionUID = 1578046825;

    /**
     * The reference instance of <code>rewards_report</code>
     */
    public static final RewardsReport REWARDS_REPORT = new RewardsReport();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RewardsReportRecord> getRecordType() {
        return RewardsReportRecord.class;
    }

    /**
     * The column <code>rewards_report.customer_id</code>.
     */
    public final TableField<RewardsReportRecord, Integer> CUSTOMER_ID = createField("customer_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('customer_customer_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>rewards_report.store_id</code>.
     */
    public final TableField<RewardsReportRecord, Short> STORE_ID = createField("store_id", org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * The column <code>rewards_report.first_name</code>.
     */
    public final TableField<RewardsReportRecord, String> FIRST_NAME = createField("first_name", org.jooq.impl.SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>rewards_report.last_name</code>.
     */
    public final TableField<RewardsReportRecord, String> LAST_NAME = createField("last_name", org.jooq.impl.SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>rewards_report.email</code>.
     */
    public final TableField<RewardsReportRecord, String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>rewards_report.address_id</code>.
     */
    public final TableField<RewardsReportRecord, Short> ADDRESS_ID = createField("address_id", org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * The column <code>rewards_report.activebool</code>.
     */
    public final TableField<RewardsReportRecord, Boolean> ACTIVEBOOL = createField("activebool", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaultValue(org.jooq.impl.DSL.field("true", org.jooq.impl.SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>rewards_report.create_date</code>.
     */
    public final TableField<RewardsReportRecord, Timestamp> CREATE_DATE = createField("create_date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("('now'::text)::date", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "", new DateAsTimestampBinding());

    /**
     * The column <code>rewards_report.last_update</code>.
     */
    public final TableField<RewardsReportRecord, Timestamp> LAST_UPDATE = createField("last_update", org.jooq.impl.SQLDataType.TIMESTAMP.defaultValue(org.jooq.impl.DSL.field("now()", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>rewards_report.active</code>.
     */
    public final TableField<RewardsReportRecord, Integer> ACTIVE = createField("active", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>rewards_report.password</code>.
     */
    public final TableField<RewardsReportRecord, String> PASSWORD = createField("password", org.jooq.impl.SQLDataType.VARCHAR(128), this, "");

    /**
     * The column <code>rewards_report.balance</code>.
     */
    public final TableField<RewardsReportRecord, BigDecimal> BALANCE = createField("balance", org.jooq.impl.SQLDataType.NUMERIC(10, 2).nullable(false).defaultValue(org.jooq.impl.DSL.field("0.0", org.jooq.impl.SQLDataType.NUMERIC)), this, "");

    /**
     * The column <code>rewards_report.avatar_url</code>.
     */
    public final TableField<RewardsReportRecord, String> AVATAR_URL = createField("avatar_url", org.jooq.impl.SQLDataType.VARCHAR(512), this, "");

    /**
     * The column <code>rewards_report.username</code>.
     */
    public final TableField<RewardsReportRecord, String> USERNAME = createField("username", org.jooq.impl.SQLDataType.VARCHAR(64), this, "");

    /**
     * Create a <code>rewards_report</code> table reference
     */
    public RewardsReport() {
        this(DSL.name("rewards_report"), null);
    }

    /**
     * Create an aliased <code>rewards_report</code> table reference
     */
    public RewardsReport(String alias) {
        this(DSL.name(alias), REWARDS_REPORT);
    }

    /**
     * Create an aliased <code>rewards_report</code> table reference
     */
    public RewardsReport(Name alias) {
        this(alias, REWARDS_REPORT);
    }

    private RewardsReport(Name alias, Table<RewardsReportRecord> aliased) {
        this(alias, aliased, new Field[2]);
    }

    private RewardsReport(Name alias, Table<RewardsReportRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> RewardsReport(Table<O> child, ForeignKey<O, RewardsReportRecord> key) {
        super(child, key, REWARDS_REPORT);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<RewardsReportRecord, Integer> getIdentity() {
        return Keys.IDENTITY_REWARDS_REPORT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RewardsReport as(String alias) {
        return new RewardsReport(DSL.name(alias), this, parameters);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RewardsReport as(Name alias) {
        return new RewardsReport(alias, this, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public RewardsReport rename(String name) {
        return new RewardsReport(DSL.name(name), null, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public RewardsReport rename(Name name) {
        return new RewardsReport(name, null, parameters);
    }

    /**
     * Call this table-valued function
     */
    public RewardsReport call(Integer minMonthlyPurchases, BigDecimal minDollarAmountPurchased) {
        return new RewardsReport(DSL.name(getName()), null, new Field[] { 
              DSL.val(minMonthlyPurchases, org.jooq.impl.SQLDataType.INTEGER)
            , DSL.val(minDollarAmountPurchased, org.jooq.impl.SQLDataType.NUMERIC)
        });
    }

    /**
     * Call this table-valued function
     */
    public RewardsReport call(Field<Integer> minMonthlyPurchases, Field<BigDecimal> minDollarAmountPurchased) {
        return new RewardsReport(DSL.name(getName()), null, new Field[] { 
              minMonthlyPurchases
            , minDollarAmountPurchased
        });
    }
}
