/*
 * This file is generated by jOOQ.
 */
package net.dualsoft.blockbuster.db.jooq.tables.pojos;


import java.sql.Timestamp;

import javax.annotation.Generated;

import net.dualsoft.blockbuster.db.jooq.tables.interfaces.IActor;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Actor implements IActor {

    private static final long serialVersionUID = -793434390;

    private Integer   actorId;
    private String    name;
    private Timestamp lastUpdate;
    private String    pictureUrl;
    private String    biography;
    private Integer   moviedbId;

    public Actor() {}

    public Actor(IActor value) {
        this.actorId = value.getActorId();
        this.name = value.getName();
        this.lastUpdate = value.getLastUpdate();
        this.pictureUrl = value.getPictureUrl();
        this.biography = value.getBiography();
        this.moviedbId = value.getMoviedbId();
    }

    public Actor(
        Integer   actorId,
        String    name,
        Timestamp lastUpdate,
        String    pictureUrl,
        String    biography,
        Integer   moviedbId
    ) {
        this.actorId = actorId;
        this.name = name;
        this.lastUpdate = lastUpdate;
        this.pictureUrl = pictureUrl;
        this.biography = biography;
        this.moviedbId = moviedbId;
    }

    @Override
    public Integer getActorId() {
        return this.actorId;
    }

    @Override
    public void setActorId(Integer actorId) {
        this.actorId = actorId;
    }

    @Override
    public String getName() {
        return this.name;
    }

    @Override
    public void setName(String name) {
        this.name = name;
    }

    @Override
    public Timestamp getLastUpdate() {
        return this.lastUpdate;
    }

    @Override
    public void setLastUpdate(Timestamp lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    @Override
    public String getPictureUrl() {
        return this.pictureUrl;
    }

    @Override
    public void setPictureUrl(String pictureUrl) {
        this.pictureUrl = pictureUrl;
    }

    @Override
    public String getBiography() {
        return this.biography;
    }

    @Override
    public void setBiography(String biography) {
        this.biography = biography;
    }

    @Override
    public Integer getMoviedbId() {
        return this.moviedbId;
    }

    @Override
    public void setMoviedbId(Integer moviedbId) {
        this.moviedbId = moviedbId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Actor (");

        sb.append(actorId);
        sb.append(", ").append(name);
        sb.append(", ").append(lastUpdate);
        sb.append(", ").append(pictureUrl);
        sb.append(", ").append(biography);
        sb.append(", ").append(moviedbId);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(IActor from) {
        setActorId(from.getActorId());
        setName(from.getName());
        setLastUpdate(from.getLastUpdate());
        setPictureUrl(from.getPictureUrl());
        setBiography(from.getBiography());
        setMoviedbId(from.getMoviedbId());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends IActor> E into(E into) {
        into.from(this);
        return into;
    }
}
