/*
 * This file is generated by jOOQ.
 */
package net.dualsoft.blockbuster.db.jooq.tables.pojos;


import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import net.dualsoft.blockbuster.db.jooq.tables.interfaces.ICustomer;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Customer implements ICustomer {

    private static final long serialVersionUID = 2130112216;

    private Integer    customerId;
    private Short      storeId;
    private String     firstName;
    private String     lastName;
    private String     email;
    private Short      addressId;
    private Boolean    activebool;
    private Timestamp  createDate;
    private Timestamp  lastUpdate;
    private Integer    active;
    private String     password;
    private BigDecimal balance;
    private String     avatarUrl;
    private String     username;

    public Customer() {}

    public Customer(ICustomer value) {
        this.customerId = value.getCustomerId();
        this.storeId = value.getStoreId();
        this.firstName = value.getFirstName();
        this.lastName = value.getLastName();
        this.email = value.getEmail();
        this.addressId = value.getAddressId();
        this.activebool = value.getActivebool();
        this.createDate = value.getCreateDate();
        this.lastUpdate = value.getLastUpdate();
        this.active = value.getActive();
        this.password = value.getPassword();
        this.balance = value.getBalance();
        this.avatarUrl = value.getAvatarUrl();
        this.username = value.getUsername();
    }

    public Customer(
        Integer    customerId,
        Short      storeId,
        String     firstName,
        String     lastName,
        String     email,
        Short      addressId,
        Boolean    activebool,
        Timestamp  createDate,
        Timestamp  lastUpdate,
        Integer    active,
        String     password,
        BigDecimal balance,
        String     avatarUrl,
        String     username
    ) {
        this.customerId = customerId;
        this.storeId = storeId;
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.addressId = addressId;
        this.activebool = activebool;
        this.createDate = createDate;
        this.lastUpdate = lastUpdate;
        this.active = active;
        this.password = password;
        this.balance = balance;
        this.avatarUrl = avatarUrl;
        this.username = username;
    }

    @Override
    public Integer getCustomerId() {
        return this.customerId;
    }

    @Override
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    @Override
    public Short getStoreId() {
        return this.storeId;
    }

    @Override
    public void setStoreId(Short storeId) {
        this.storeId = storeId;
    }

    @Override
    public String getFirstName() {
        return this.firstName;
    }

    @Override
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    @Override
    public String getLastName() {
        return this.lastName;
    }

    @Override
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    @Override
    public String getEmail() {
        return this.email;
    }

    @Override
    public void setEmail(String email) {
        this.email = email;
    }

    @Override
    public Short getAddressId() {
        return this.addressId;
    }

    @Override
    public void setAddressId(Short addressId) {
        this.addressId = addressId;
    }

    @Override
    public Boolean getActivebool() {
        return this.activebool;
    }

    @Override
    public void setActivebool(Boolean activebool) {
        this.activebool = activebool;
    }

    @Override
    public Timestamp getCreateDate() {
        return this.createDate;
    }

    @Override
    public void setCreateDate(Timestamp createDate) {
        this.createDate = createDate;
    }

    @Override
    public Timestamp getLastUpdate() {
        return this.lastUpdate;
    }

    @Override
    public void setLastUpdate(Timestamp lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    @Override
    public Integer getActive() {
        return this.active;
    }

    @Override
    public void setActive(Integer active) {
        this.active = active;
    }

    @Override
    public String getPassword() {
        return this.password;
    }

    @Override
    public void setPassword(String password) {
        this.password = password;
    }

    @Override
    public BigDecimal getBalance() {
        return this.balance;
    }

    @Override
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    @Override
    public String getAvatarUrl() {
        return this.avatarUrl;
    }

    @Override
    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl;
    }

    @Override
    public String getUsername() {
        return this.username;
    }

    @Override
    public void setUsername(String username) {
        this.username = username;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Customer (");

        sb.append(customerId);
        sb.append(", ").append(storeId);
        sb.append(", ").append(firstName);
        sb.append(", ").append(lastName);
        sb.append(", ").append(email);
        sb.append(", ").append(addressId);
        sb.append(", ").append(activebool);
        sb.append(", ").append(createDate);
        sb.append(", ").append(lastUpdate);
        sb.append(", ").append(active);
        sb.append(", ").append(password);
        sb.append(", ").append(balance);
        sb.append(", ").append(avatarUrl);
        sb.append(", ").append(username);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ICustomer from) {
        setCustomerId(from.getCustomerId());
        setStoreId(from.getStoreId());
        setFirstName(from.getFirstName());
        setLastName(from.getLastName());
        setEmail(from.getEmail());
        setAddressId(from.getAddressId());
        setActivebool(from.getActivebool());
        setCreateDate(from.getCreateDate());
        setLastUpdate(from.getLastUpdate());
        setActive(from.getActive());
        setPassword(from.getPassword());
        setBalance(from.getBalance());
        setAvatarUrl(from.getAvatarUrl());
        setUsername(from.getUsername());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ICustomer> E into(E into) {
        into.from(this);
        return into;
    }
}
