/*
 * This file is generated by jOOQ.
 */
package net.dualsoft.blockbuster.db.jooq.tables.pojos;


import javax.annotation.Generated;

import net.dualsoft.blockbuster.db.jooq.tables.interfaces.IFilmNotInStock;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FilmNotInStock implements IFilmNotInStock {

    private static final long serialVersionUID = 40980098;

    private Integer pFilmCount;

    public FilmNotInStock() {}

    public FilmNotInStock(IFilmNotInStock value) {
        this.pFilmCount = value.getPFilmCount();
    }

    public FilmNotInStock(
        Integer pFilmCount
    ) {
        this.pFilmCount = pFilmCount;
    }

    @Override
    public Integer getPFilmCount() {
        return this.pFilmCount;
    }

    @Override
    public void setPFilmCount(Integer pFilmCount) {
        this.pFilmCount = pFilmCount;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("FilmNotInStock (");

        sb.append(pFilmCount);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(IFilmNotInStock from) {
        setPFilmCount(from.getPFilmCount());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends IFilmNotInStock> E into(E into) {
        into.from(this);
        return into;
    }
}
