/*
 * This file is generated by jOOQ.
 */
package net.dualsoft.blockbuster.db.jooq.tables.pojos;


import java.sql.Timestamp;

import javax.annotation.Generated;

import net.dualsoft.blockbuster.db.jooq.tables.interfaces.IFilmCategory;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FilmCategory implements IFilmCategory {

    private static final long serialVersionUID = -23398068;

    private Short     filmId;
    private Short     categoryId;
    private Timestamp lastUpdate;

    public FilmCategory() {}

    public FilmCategory(IFilmCategory value) {
        this.filmId = value.getFilmId();
        this.categoryId = value.getCategoryId();
        this.lastUpdate = value.getLastUpdate();
    }

    public FilmCategory(
        Short     filmId,
        Short     categoryId,
        Timestamp lastUpdate
    ) {
        this.filmId = filmId;
        this.categoryId = categoryId;
        this.lastUpdate = lastUpdate;
    }

    @Override
    public Short getFilmId() {
        return this.filmId;
    }

    @Override
    public void setFilmId(Short filmId) {
        this.filmId = filmId;
    }

    @Override
    public Short getCategoryId() {
        return this.categoryId;
    }

    @Override
    public void setCategoryId(Short categoryId) {
        this.categoryId = categoryId;
    }

    @Override
    public Timestamp getLastUpdate() {
        return this.lastUpdate;
    }

    @Override
    public void setLastUpdate(Timestamp lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("FilmCategory (");

        sb.append(filmId);
        sb.append(", ").append(categoryId);
        sb.append(", ").append(lastUpdate);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(IFilmCategory from) {
        setFilmId(from.getFilmId());
        setCategoryId(from.getCategoryId());
        setLastUpdate(from.getLastUpdate());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends IFilmCategory> E into(E into) {
        into.from(this);
        return into;
    }
}
