/*
 * This file is generated by jOOQ.
 */
package net.dualsoft.blockbuster.db.jooq.tables.pojos;


import java.sql.Timestamp;

import javax.annotation.Generated;

import net.dualsoft.blockbuster.db.jooq.tables.interfaces.IInventory;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Inventory implements IInventory {

    private static final long serialVersionUID = -1216304322;

    private Integer   inventoryId;
    private Short     filmId;
    private Short     storeId;
    private Timestamp lastUpdate;

    public Inventory() {}

    public Inventory(IInventory value) {
        this.inventoryId = value.getInventoryId();
        this.filmId = value.getFilmId();
        this.storeId = value.getStoreId();
        this.lastUpdate = value.getLastUpdate();
    }

    public Inventory(
        Integer   inventoryId,
        Short     filmId,
        Short     storeId,
        Timestamp lastUpdate
    ) {
        this.inventoryId = inventoryId;
        this.filmId = filmId;
        this.storeId = storeId;
        this.lastUpdate = lastUpdate;
    }

    @Override
    public Integer getInventoryId() {
        return this.inventoryId;
    }

    @Override
    public void setInventoryId(Integer inventoryId) {
        this.inventoryId = inventoryId;
    }

    @Override
    public Short getFilmId() {
        return this.filmId;
    }

    @Override
    public void setFilmId(Short filmId) {
        this.filmId = filmId;
    }

    @Override
    public Short getStoreId() {
        return this.storeId;
    }

    @Override
    public void setStoreId(Short storeId) {
        this.storeId = storeId;
    }

    @Override
    public Timestamp getLastUpdate() {
        return this.lastUpdate;
    }

    @Override
    public void setLastUpdate(Timestamp lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Inventory (");

        sb.append(inventoryId);
        sb.append(", ").append(filmId);
        sb.append(", ").append(storeId);
        sb.append(", ").append(lastUpdate);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(IInventory from) {
        setInventoryId(from.getInventoryId());
        setFilmId(from.getFilmId());
        setStoreId(from.getStoreId());
        setLastUpdate(from.getLastUpdate());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends IInventory> E into(E into) {
        into.from(this);
        return into;
    }
}
