/*
 * This file is generated by jOOQ.
 */
package net.dualsoft.blockbuster.db.jooq.tables.pojos;


import java.sql.Timestamp;

import javax.annotation.Generated;

import net.dualsoft.blockbuster.db.jooq.enums.RequestStatus;
import net.dualsoft.blockbuster.db.jooq.tables.interfaces.IRentalRequest;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RentalRequest implements IRentalRequest {

    private static final long serialVersionUID = 1236726155;

    private Integer       rentalRequestId;
    private Integer       filmId;
    private Integer       storeId;
    private Integer       customerId;
    private RequestStatus status;
    private Timestamp     createDate;
    private Timestamp     lastUpdate;

    public RentalRequest() {}

    public RentalRequest(IRentalRequest value) {
        this.rentalRequestId = value.getRentalRequestId();
        this.filmId = value.getFilmId();
        this.storeId = value.getStoreId();
        this.customerId = value.getCustomerId();
        this.status = value.getStatus();
        this.createDate = value.getCreateDate();
        this.lastUpdate = value.getLastUpdate();
    }

    public RentalRequest(
        Integer       rentalRequestId,
        Integer       filmId,
        Integer       storeId,
        Integer       customerId,
        RequestStatus status,
        Timestamp     createDate,
        Timestamp     lastUpdate
    ) {
        this.rentalRequestId = rentalRequestId;
        this.filmId = filmId;
        this.storeId = storeId;
        this.customerId = customerId;
        this.status = status;
        this.createDate = createDate;
        this.lastUpdate = lastUpdate;
    }

    @Override
    public Integer getRentalRequestId() {
        return this.rentalRequestId;
    }

    @Override
    public void setRentalRequestId(Integer rentalRequestId) {
        this.rentalRequestId = rentalRequestId;
    }

    @Override
    public Integer getFilmId() {
        return this.filmId;
    }

    @Override
    public void setFilmId(Integer filmId) {
        this.filmId = filmId;
    }

    @Override
    public Integer getStoreId() {
        return this.storeId;
    }

    @Override
    public void setStoreId(Integer storeId) {
        this.storeId = storeId;
    }

    @Override
    public Integer getCustomerId() {
        return this.customerId;
    }

    @Override
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    @Override
    public RequestStatus getStatus() {
        return this.status;
    }

    @Override
    public void setStatus(RequestStatus status) {
        this.status = status;
    }

    @Override
    public Timestamp getCreateDate() {
        return this.createDate;
    }

    @Override
    public void setCreateDate(Timestamp createDate) {
        this.createDate = createDate;
    }

    @Override
    public Timestamp getLastUpdate() {
        return this.lastUpdate;
    }

    @Override
    public void setLastUpdate(Timestamp lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("RentalRequest (");

        sb.append(rentalRequestId);
        sb.append(", ").append(filmId);
        sb.append(", ").append(storeId);
        sb.append(", ").append(customerId);
        sb.append(", ").append(status);
        sb.append(", ").append(createDate);
        sb.append(", ").append(lastUpdate);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(IRentalRequest from) {
        setRentalRequestId(from.getRentalRequestId());
        setFilmId(from.getFilmId());
        setStoreId(from.getStoreId());
        setCustomerId(from.getCustomerId());
        setStatus(from.getStatus());
        setCreateDate(from.getCreateDate());
        setLastUpdate(from.getLastUpdate());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends IRentalRequest> E into(E into) {
        into.from(this);
        return into;
    }
}
