/*
 * This file is generated by jOOQ.
 */
package net.dualsoft.blockbuster.db.jooq.tables.pojos;


import java.sql.Timestamp;

import javax.annotation.Generated;

import net.dualsoft.blockbuster.db.jooq.tables.interfaces.IRental;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Rental implements IRental {

    private static final long serialVersionUID = 1286568158;

    private Integer   rentalId;
    private Timestamp rentalDate;
    private Integer   inventoryId;
    private Short     customerId;
    private Timestamp returnDate;
    private Short     staffId;
    private Timestamp lastUpdate;

    public Rental() {}

    public Rental(IRental value) {
        this.rentalId = value.getRentalId();
        this.rentalDate = value.getRentalDate();
        this.inventoryId = value.getInventoryId();
        this.customerId = value.getCustomerId();
        this.returnDate = value.getReturnDate();
        this.staffId = value.getStaffId();
        this.lastUpdate = value.getLastUpdate();
    }

    public Rental(
        Integer   rentalId,
        Timestamp rentalDate,
        Integer   inventoryId,
        Short     customerId,
        Timestamp returnDate,
        Short     staffId,
        Timestamp lastUpdate
    ) {
        this.rentalId = rentalId;
        this.rentalDate = rentalDate;
        this.inventoryId = inventoryId;
        this.customerId = customerId;
        this.returnDate = returnDate;
        this.staffId = staffId;
        this.lastUpdate = lastUpdate;
    }

    @Override
    public Integer getRentalId() {
        return this.rentalId;
    }

    @Override
    public void setRentalId(Integer rentalId) {
        this.rentalId = rentalId;
    }

    @Override
    public Timestamp getRentalDate() {
        return this.rentalDate;
    }

    @Override
    public void setRentalDate(Timestamp rentalDate) {
        this.rentalDate = rentalDate;
    }

    @Override
    public Integer getInventoryId() {
        return this.inventoryId;
    }

    @Override
    public void setInventoryId(Integer inventoryId) {
        this.inventoryId = inventoryId;
    }

    @Override
    public Short getCustomerId() {
        return this.customerId;
    }

    @Override
    public void setCustomerId(Short customerId) {
        this.customerId = customerId;
    }

    @Override
    public Timestamp getReturnDate() {
        return this.returnDate;
    }

    @Override
    public void setReturnDate(Timestamp returnDate) {
        this.returnDate = returnDate;
    }

    @Override
    public Short getStaffId() {
        return this.staffId;
    }

    @Override
    public void setStaffId(Short staffId) {
        this.staffId = staffId;
    }

    @Override
    public Timestamp getLastUpdate() {
        return this.lastUpdate;
    }

    @Override
    public void setLastUpdate(Timestamp lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Rental (");

        sb.append(rentalId);
        sb.append(", ").append(rentalDate);
        sb.append(", ").append(inventoryId);
        sb.append(", ").append(customerId);
        sb.append(", ").append(returnDate);
        sb.append(", ").append(staffId);
        sb.append(", ").append(lastUpdate);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(IRental from) {
        setRentalId(from.getRentalId());
        setRentalDate(from.getRentalDate());
        setInventoryId(from.getInventoryId());
        setCustomerId(from.getCustomerId());
        setReturnDate(from.getReturnDate());
        setStaffId(from.getStaffId());
        setLastUpdate(from.getLastUpdate());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends IRental> E into(E into) {
        into.from(this);
        return into;
    }
}
