/*
 * This file is generated by jOOQ.
 */
package net.dualsoft.blockbuster.db.jooq.tables.pojos;


import java.sql.Timestamp;

import javax.annotation.Generated;

import net.dualsoft.blockbuster.db.jooq.tables.interfaces.IStaff;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Staff implements IStaff {

    private static final long serialVersionUID = 493403913;

    private Integer   staffId;
    private String    firstName;
    private String    lastName;
    private Short     addressId;
    private String    email;
    private Short     storeId;
    private Boolean   active;
    private String    username;
    private String    password;
    private Timestamp lastUpdate;
    private String    picture;

    public Staff() {}

    public Staff(IStaff value) {
        this.staffId = value.getStaffId();
        this.firstName = value.getFirstName();
        this.lastName = value.getLastName();
        this.addressId = value.getAddressId();
        this.email = value.getEmail();
        this.storeId = value.getStoreId();
        this.active = value.getActive();
        this.username = value.getUsername();
        this.password = value.getPassword();
        this.lastUpdate = value.getLastUpdate();
        this.picture = value.getPicture();
    }

    public Staff(
        Integer   staffId,
        String    firstName,
        String    lastName,
        Short     addressId,
        String    email,
        Short     storeId,
        Boolean   active,
        String    username,
        String    password,
        Timestamp lastUpdate,
        String    picture
    ) {
        this.staffId = staffId;
        this.firstName = firstName;
        this.lastName = lastName;
        this.addressId = addressId;
        this.email = email;
        this.storeId = storeId;
        this.active = active;
        this.username = username;
        this.password = password;
        this.lastUpdate = lastUpdate;
        this.picture = picture;
    }

    @Override
    public Integer getStaffId() {
        return this.staffId;
    }

    @Override
    public void setStaffId(Integer staffId) {
        this.staffId = staffId;
    }

    @Override
    public String getFirstName() {
        return this.firstName;
    }

    @Override
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    @Override
    public String getLastName() {
        return this.lastName;
    }

    @Override
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    @Override
    public Short getAddressId() {
        return this.addressId;
    }

    @Override
    public void setAddressId(Short addressId) {
        this.addressId = addressId;
    }

    @Override
    public String getEmail() {
        return this.email;
    }

    @Override
    public void setEmail(String email) {
        this.email = email;
    }

    @Override
    public Short getStoreId() {
        return this.storeId;
    }

    @Override
    public void setStoreId(Short storeId) {
        this.storeId = storeId;
    }

    @Override
    public Boolean getActive() {
        return this.active;
    }

    @Override
    public void setActive(Boolean active) {
        this.active = active;
    }

    @Override
    public String getUsername() {
        return this.username;
    }

    @Override
    public void setUsername(String username) {
        this.username = username;
    }

    @Override
    public String getPassword() {
        return this.password;
    }

    @Override
    public void setPassword(String password) {
        this.password = password;
    }

    @Override
    public Timestamp getLastUpdate() {
        return this.lastUpdate;
    }

    @Override
    public void setLastUpdate(Timestamp lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    @Override
    public String getPicture() {
        return this.picture;
    }

    @Override
    public void setPicture(String picture) {
        this.picture = picture;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Staff (");

        sb.append(staffId);
        sb.append(", ").append(firstName);
        sb.append(", ").append(lastName);
        sb.append(", ").append(addressId);
        sb.append(", ").append(email);
        sb.append(", ").append(storeId);
        sb.append(", ").append(active);
        sb.append(", ").append(username);
        sb.append(", ").append(password);
        sb.append(", ").append(lastUpdate);
        sb.append(", ").append(picture);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(IStaff from) {
        setStaffId(from.getStaffId());
        setFirstName(from.getFirstName());
        setLastName(from.getLastName());
        setAddressId(from.getAddressId());
        setEmail(from.getEmail());
        setStoreId(from.getStoreId());
        setActive(from.getActive());
        setUsername(from.getUsername());
        setPassword(from.getPassword());
        setLastUpdate(from.getLastUpdate());
        setPicture(from.getPicture());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends IStaff> E into(E into) {
        into.from(this);
        return into;
    }
}
