/*
 * This file is generated by jOOQ.
 */
package net.dualsoft.blockbuster.db.jooq.tables.pojos;


import java.sql.Timestamp;

import javax.annotation.Generated;

import net.dualsoft.blockbuster.db.jooq.tables.interfaces.IStore;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Store implements IStore {

    private static final long serialVersionUID = 274897945;

    private Integer   storeId;
    private Short     managerStaffId;
    private Short     addressId;
    private Timestamp lastUpdate;

    public Store() {}

    public Store(IStore value) {
        this.storeId = value.getStoreId();
        this.managerStaffId = value.getManagerStaffId();
        this.addressId = value.getAddressId();
        this.lastUpdate = value.getLastUpdate();
    }

    public Store(
        Integer   storeId,
        Short     managerStaffId,
        Short     addressId,
        Timestamp lastUpdate
    ) {
        this.storeId = storeId;
        this.managerStaffId = managerStaffId;
        this.addressId = addressId;
        this.lastUpdate = lastUpdate;
    }

    @Override
    public Integer getStoreId() {
        return this.storeId;
    }

    @Override
    public void setStoreId(Integer storeId) {
        this.storeId = storeId;
    }

    @Override
    public Short getManagerStaffId() {
        return this.managerStaffId;
    }

    @Override
    public void setManagerStaffId(Short managerStaffId) {
        this.managerStaffId = managerStaffId;
    }

    @Override
    public Short getAddressId() {
        return this.addressId;
    }

    @Override
    public void setAddressId(Short addressId) {
        this.addressId = addressId;
    }

    @Override
    public Timestamp getLastUpdate() {
        return this.lastUpdate;
    }

    @Override
    public void setLastUpdate(Timestamp lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Store (");

        sb.append(storeId);
        sb.append(", ").append(managerStaffId);
        sb.append(", ").append(addressId);
        sb.append(", ").append(lastUpdate);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(IStore from) {
        setStoreId(from.getStoreId());
        setManagerStaffId(from.getManagerStaffId());
        setAddressId(from.getAddressId());
        setLastUpdate(from.getLastUpdate());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends IStore> E into(E into) {
        into.from(this);
        return into;
    }
}
