/*
 * This file is generated by jOOQ.
 */
package net.dualsoft.blockbuster.db.jooq.tables.pojos;


import java.sql.Timestamp;

import javax.annotation.Generated;

import net.dualsoft.blockbuster.db.jooq.tables.interfaces.IUserNotification;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserNotification implements IUserNotification {

    private static final long serialVersionUID = -2132887860;

    private Integer   userNotificationId;
    private Integer   customerId;
    private String    title;
    private String    notificationText;
    private Boolean   read;
    private Timestamp lastUpdate;

    public UserNotification() {}

    public UserNotification(IUserNotification value) {
        this.userNotificationId = value.getUserNotificationId();
        this.customerId = value.getCustomerId();
        this.title = value.getTitle();
        this.notificationText = value.getNotificationText();
        this.read = value.getRead();
        this.lastUpdate = value.getLastUpdate();
    }

    public UserNotification(
        Integer   userNotificationId,
        Integer   customerId,
        String    title,
        String    notificationText,
        Boolean   read,
        Timestamp lastUpdate
    ) {
        this.userNotificationId = userNotificationId;
        this.customerId = customerId;
        this.title = title;
        this.notificationText = notificationText;
        this.read = read;
        this.lastUpdate = lastUpdate;
    }

    @Override
    public Integer getUserNotificationId() {
        return this.userNotificationId;
    }

    @Override
    public void setUserNotificationId(Integer userNotificationId) {
        this.userNotificationId = userNotificationId;
    }

    @Override
    public Integer getCustomerId() {
        return this.customerId;
    }

    @Override
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    @Override
    public String getTitle() {
        return this.title;
    }

    @Override
    public void setTitle(String title) {
        this.title = title;
    }

    @Override
    public String getNotificationText() {
        return this.notificationText;
    }

    @Override
    public void setNotificationText(String notificationText) {
        this.notificationText = notificationText;
    }

    @Override
    public Boolean getRead() {
        return this.read;
    }

    @Override
    public void setRead(Boolean read) {
        this.read = read;
    }

    @Override
    public Timestamp getLastUpdate() {
        return this.lastUpdate;
    }

    @Override
    public void setLastUpdate(Timestamp lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserNotification (");

        sb.append(userNotificationId);
        sb.append(", ").append(customerId);
        sb.append(", ").append(title);
        sb.append(", ").append(notificationText);
        sb.append(", ").append(read);
        sb.append(", ").append(lastUpdate);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(IUserNotification from) {
        setUserNotificationId(from.getUserNotificationId());
        setCustomerId(from.getCustomerId());
        setTitle(from.getTitle());
        setNotificationText(from.getNotificationText());
        setRead(from.getRead());
        setLastUpdate(from.getLastUpdate());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends IUserNotification> E into(E into) {
        into.from(this);
        return into;
    }
}
