/*
 * This file is generated by jOOQ.
 */
package net.dualsoft.blockbuster.db.jooq.tables.records;


import javax.annotation.Generated;

import net.dualsoft.blockbuster.db.jooq.tables.FilmNotInStock;
import net.dualsoft.blockbuster.db.jooq.tables.interfaces.IFilmNotInStock;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FilmNotInStockRecord extends TableRecordImpl<FilmNotInStockRecord> implements Record1<Integer>, IFilmNotInStock {

    private static final long serialVersionUID = -1834398264;

    /**
     * Setter for <code>film_not_in_stock.p_film_count</code>.
     */
    @Override
    public void setPFilmCount(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>film_not_in_stock.p_film_count</code>.
     */
    @Override
    public Integer getPFilmCount() {
        return (Integer) get(0);
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row1<Integer> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row1<Integer> valuesRow() {
        return (Row1) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return FilmNotInStock.FILM_NOT_IN_STOCK.P_FILM_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getPFilmCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getPFilmCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FilmNotInStockRecord value1(Integer value) {
        setPFilmCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FilmNotInStockRecord values(Integer value1) {
        value1(value1);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(IFilmNotInStock from) {
        setPFilmCount(from.getPFilmCount());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends IFilmNotInStock> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FilmNotInStockRecord
     */
    public FilmNotInStockRecord() {
        super(FilmNotInStock.FILM_NOT_IN_STOCK);
    }

    /**
     * Create a detached, initialised FilmNotInStockRecord
     */
    public FilmNotInStockRecord(Integer pFilmCount) {
        super(FilmNotInStock.FILM_NOT_IN_STOCK);

        set(0, pFilmCount);
    }
}
