/*
 * This file is generated by jOOQ.
 */
package net.dualsoft.blockbuster.db.jooq.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import net.dualsoft.blockbuster.db.jooq.enums.RequestStatus;
import net.dualsoft.blockbuster.db.jooq.tables.RentalRequest;
import net.dualsoft.blockbuster.db.jooq.tables.interfaces.IRentalRequest;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RentalRequestRecord extends UpdatableRecordImpl<RentalRequestRecord> implements Record7<Integer, Integer, Integer, Integer, RequestStatus, Timestamp, Timestamp>, IRentalRequest {

    private static final long serialVersionUID = 819767990;

    /**
     * Setter for <code>rental_request.rental_request_id</code>.
     */
    @Override
    public void setRentalRequestId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>rental_request.rental_request_id</code>.
     */
    @Override
    public Integer getRentalRequestId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>rental_request.film_id</code>.
     */
    @Override
    public void setFilmId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>rental_request.film_id</code>.
     */
    @Override
    public Integer getFilmId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>rental_request.store_id</code>.
     */
    @Override
    public void setStoreId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>rental_request.store_id</code>.
     */
    @Override
    public Integer getStoreId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>rental_request.customer_id</code>.
     */
    @Override
    public void setCustomerId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>rental_request.customer_id</code>.
     */
    @Override
    public Integer getCustomerId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>rental_request.status</code>.
     */
    @Override
    public void setStatus(RequestStatus value) {
        set(4, value);
    }

    /**
     * Getter for <code>rental_request.status</code>.
     */
    @Override
    public RequestStatus getStatus() {
        return (RequestStatus) get(4);
    }

    /**
     * Setter for <code>rental_request.create_date</code>.
     */
    @Override
    public void setCreateDate(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>rental_request.create_date</code>.
     */
    @Override
    public Timestamp getCreateDate() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>rental_request.last_update</code>.
     */
    @Override
    public void setLastUpdate(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>rental_request.last_update</code>.
     */
    @Override
    public Timestamp getLastUpdate() {
        return (Timestamp) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, Integer, Integer, RequestStatus, Timestamp, Timestamp> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, Integer, Integer, RequestStatus, Timestamp, Timestamp> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return RentalRequest.RENTAL_REQUEST.RENTAL_REQUEST_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return RentalRequest.RENTAL_REQUEST.FILM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return RentalRequest.RENTAL_REQUEST.STORE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return RentalRequest.RENTAL_REQUEST.CUSTOMER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<RequestStatus> field5() {
        return RentalRequest.RENTAL_REQUEST.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return RentalRequest.RENTAL_REQUEST.CREATE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return RentalRequest.RENTAL_REQUEST.LAST_UPDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getRentalRequestId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getFilmId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getStoreId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getCustomerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RequestStatus component5() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getLastUpdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getRentalRequestId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getFilmId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getStoreId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getCustomerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RequestStatus value5() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getLastUpdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RentalRequestRecord value1(Integer value) {
        setRentalRequestId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RentalRequestRecord value2(Integer value) {
        setFilmId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RentalRequestRecord value3(Integer value) {
        setStoreId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RentalRequestRecord value4(Integer value) {
        setCustomerId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RentalRequestRecord value5(RequestStatus value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RentalRequestRecord value6(Timestamp value) {
        setCreateDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RentalRequestRecord value7(Timestamp value) {
        setLastUpdate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RentalRequestRecord values(Integer value1, Integer value2, Integer value3, Integer value4, RequestStatus value5, Timestamp value6, Timestamp value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(IRentalRequest from) {
        setRentalRequestId(from.getRentalRequestId());
        setFilmId(from.getFilmId());
        setStoreId(from.getStoreId());
        setCustomerId(from.getCustomerId());
        setStatus(from.getStatus());
        setCreateDate(from.getCreateDate());
        setLastUpdate(from.getLastUpdate());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends IRentalRequest> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RentalRequestRecord
     */
    public RentalRequestRecord() {
        super(RentalRequest.RENTAL_REQUEST);
    }

    /**
     * Create a detached, initialised RentalRequestRecord
     */
    public RentalRequestRecord(Integer rentalRequestId, Integer filmId, Integer storeId, Integer customerId, RequestStatus status, Timestamp createDate, Timestamp lastUpdate) {
        super(RentalRequest.RENTAL_REQUEST);

        set(0, rentalRequestId);
        set(1, filmId);
        set(2, storeId);
        set(3, customerId);
        set(4, status);
        set(5, createDate);
        set(6, lastUpdate);
    }
}
