/*
 * This file is generated by jOOQ.
 */
package net.dualsoft.blockbuster.db.jooq.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import net.dualsoft.blockbuster.db.jooq.tables.UserNotification;
import net.dualsoft.blockbuster.db.jooq.tables.interfaces.IUserNotification;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserNotificationRecord extends UpdatableRecordImpl<UserNotificationRecord> implements Record6<Integer, Integer, String, String, Boolean, Timestamp>, IUserNotification {

    private static final long serialVersionUID = 800162515;

    /**
     * Setter for <code>user_notification.user_notification_id</code>.
     */
    @Override
    public void setUserNotificationId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>user_notification.user_notification_id</code>.
     */
    @Override
    public Integer getUserNotificationId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>user_notification.customer_id</code>.
     */
    @Override
    public void setCustomerId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>user_notification.customer_id</code>.
     */
    @Override
    public Integer getCustomerId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>user_notification.title</code>.
     */
    @Override
    public void setTitle(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>user_notification.title</code>.
     */
    @Override
    public String getTitle() {
        return (String) get(2);
    }

    /**
     * Setter for <code>user_notification.notification_text</code>.
     */
    @Override
    public void setNotificationText(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>user_notification.notification_text</code>.
     */
    @Override
    public String getNotificationText() {
        return (String) get(3);
    }

    /**
     * Setter for <code>user_notification.read</code>.
     */
    @Override
    public void setRead(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>user_notification.read</code>.
     */
    @Override
    public Boolean getRead() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>user_notification.last_update</code>.
     */
    @Override
    public void setLastUpdate(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>user_notification.last_update</code>.
     */
    @Override
    public Timestamp getLastUpdate() {
        return (Timestamp) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, String, String, Boolean, Timestamp> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, String, String, Boolean, Timestamp> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return UserNotification.USER_NOTIFICATION.USER_NOTIFICATION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return UserNotification.USER_NOTIFICATION.CUSTOMER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return UserNotification.USER_NOTIFICATION.TITLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return UserNotification.USER_NOTIFICATION.NOTIFICATION_TEXT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field5() {
        return UserNotification.USER_NOTIFICATION.READ;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return UserNotification.USER_NOTIFICATION.LAST_UPDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getUserNotificationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getCustomerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getNotificationText();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component5() {
        return getRead();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getLastUpdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getUserNotificationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getCustomerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getNotificationText();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value5() {
        return getRead();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getLastUpdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserNotificationRecord value1(Integer value) {
        setUserNotificationId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserNotificationRecord value2(Integer value) {
        setCustomerId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserNotificationRecord value3(String value) {
        setTitle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserNotificationRecord value4(String value) {
        setNotificationText(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserNotificationRecord value5(Boolean value) {
        setRead(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserNotificationRecord value6(Timestamp value) {
        setLastUpdate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserNotificationRecord values(Integer value1, Integer value2, String value3, String value4, Boolean value5, Timestamp value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(IUserNotification from) {
        setUserNotificationId(from.getUserNotificationId());
        setCustomerId(from.getCustomerId());
        setTitle(from.getTitle());
        setNotificationText(from.getNotificationText());
        setRead(from.getRead());
        setLastUpdate(from.getLastUpdate());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends IUserNotification> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserNotificationRecord
     */
    public UserNotificationRecord() {
        super(UserNotification.USER_NOTIFICATION);
    }

    /**
     * Create a detached, initialised UserNotificationRecord
     */
    public UserNotificationRecord(Integer userNotificationId, Integer customerId, String title, String notificationText, Boolean read, Timestamp lastUpdate) {
        super(UserNotification.USER_NOTIFICATION);

        set(0, userNotificationId);
        set(1, customerId);
        set(2, title);
        set(3, notificationText);
        set(4, read);
        set(5, lastUpdate);
    }
}
